/** Generated from prompts/generated_code_download_typescript.prompt. */
const identifier = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

function assertSource(source: string): void {
  if (!source.trim()) throw new TypeError("Generated source must not be empty.");
}

export function toGeneratedTypeScriptModule(source: string, exportName = "generatedCode"): string {
  assertSource(source);
  if (!identifier.test(exportName)) throw new TypeError("exportName must be a valid TypeScript identifier.");
  return `/** Generated by co-prompt. */\nexport const ${exportName}: string = ${JSON.stringify(source)};\n\nexport default ${exportName};\n`;
}

export function downloadGeneratedTypeScript(source: string, filename = "coprompt-generated.ts", exportName = "generatedCode"): void {
  if (typeof document === "undefined" || typeof URL === "undefined") throw new Error("Downloading generated code requires a browser.");
  const blob = new Blob([toGeneratedTypeScriptModule(source, exportName)], { type: "text/typescript;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename.trim().endsWith(".ts") ? filename.trim() : `${filename.trim() || "coprompt-generated"}.ts`;
  anchor.style.display = "none";
  document.body.append(anchor);
  anchor.click();
  anchor.remove();
  window.setTimeout(() => URL.revokeObjectURL(url), 0);
}
