/** Generated from prompts/generated_code_download_javascript.prompt. */
const identifier = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

function assertSource(source: string): void {
  if (!source.trim()) throw new TypeError("Generated source must not be empty.");
}

export function toGeneratedJavaScriptModule(source: string, exportName = "generatedCode"): string {
  assertSource(source);
  if (!identifier.test(exportName)) throw new TypeError("exportName must be a valid JavaScript identifier.");
  return `/** Generated by co-prompt. */\nexport const ${exportName} = ${JSON.stringify(source)};\n\nexport default ${exportName};\n`;
}

export function downloadGeneratedJavaScript(source: string, filename = "coprompt-generated.js", exportName = "generatedCode"): void {
  if (typeof document === "undefined" || typeof URL === "undefined") throw new Error("Downloading generated code requires a browser.");
  const blob = new Blob([toGeneratedJavaScriptModule(source, exportName)], { type: "text/javascript;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename.trim().endsWith(".js") ? filename.trim() : `${filename.trim() || "coprompt-generated"}.js`;
  anchor.style.display = "none";
  document.body.append(anchor);
  anchor.click();
  anchor.remove();
  window.setTimeout(() => URL.revokeObjectURL(url), 0);
}
